# Generated by Django 5.0.3 on 2024-03-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress2',
            new_name='address2',
        ),
    ]
